# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6031501cb1009dd1755723778ca48d14ca8b7c822127bf33335d60c643db9b9c09b9ddcf1edf9985f1213271520055ae3eeae66204024bc1201a1fa5902dafe1

test:
  secret_key_base: 93ff678534ecfa2c4919de2a990611124c9a4de340221898c561952bc9f239b4fab0b6b1ed3b35e58206dd778a5124f077a7d7ce44214cbd7938b609344698d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
